name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: yarn

      - name: build project
        run: yarn run build

      - name: Build the Docker image
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password=${{ secrets.DOCKER_PASSWORD }}
          docker build -t noctis-player:latest .
          docker tag noctis-player registry.cn-hangzhou.aliyuncs.com/zeekcheung/noctis-player:latest
          docker push registry.cn-hangzhou.aliyuncs.com/zeekcheung/noctis-player:latest
          
      - name: ssh docker login
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          script: cd ~ && sh noctis-player-deploy.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}
